Update keep_alive.yml
remove trailing spaces after backslash on multi-line command

diff --git a/.github/workflows/keep_alive.yml b/.github/workflows/keep_alive.yml
--- a/.github/workflows/keep_alive.yml
+++ b/.github/workflows/keep_alive.yml
@@ -52,8 +52,8 @@ jobs:
         run: |
           PAYLOAD=$(jq -n --argjson o '${{ steps.check-workflows.outputs.results }}' '{"Outcome": $o}')
           echo $PAYLOAD
-          jq -e 'has("Outcome") and (.Outcome | type=="array")' <<<"$PAYLOAD" || { echo "Error: Outcome key is missing or not an array"} \ 
-            && jq -c '.Outcome[]' <<<"$PAYLOAD" \ 
+          jq -e 'has("Outcome") and (.Outcome | type=="array")' <<<"$PAYLOAD" || { echo "Error: Outcome key is missing or not an array"} \
+            && jq -c '.Outcome[]' <<<"$PAYLOAD" \
             | while read i; do curl -X POST -H 'Content-Type: application/json' --data $i "${{ vars.SLACK_KEEPALIVE_WEBHOOK_URL }}"; done
           
           
